FROM chosenken/steamcmd_base
MAINTAINER chosenken@gmail.com

ENV REFRESHEDON 02-17-2015

USER appuser
ENV GAME left4dead2
ENV APP_ID 222860

VOLUME $DATADIR

ENV GAMEDIR $DATADIR/$GAME
RUN mkdir -p $GAMEDIR

ADD ./scripts $SCRIPTSDIR
